/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  backoffice: {
    Auth: () => import('#controllers/backoffice/auth_controller'),
    Dashboard: () => import('#controllers/backoffice/dashboard_controller'),
  },
  HealthChecks: () => import('#controllers/health_checks_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
}
