/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ClientSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'email', 'firstName', 'id', 'lastName', 'phone', 'updatedAt'] as const
  $columns = ClientSchema.$columns
  @column()
  declare address: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column()
  declare phone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PackageLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'fromStatus', 'id', 'packageId', 'toStatus', 'userId'] as const
  $columns = PackageLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromStatus: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare packageId: number
  @column()
  declare toStatus: string | null
  @column()
  declare userId: number
}

export class PackageSchema extends BaseModel {
  static $columns = ['clientId', 'createdAt', 'description', 'designation', 'estimatedDeliveryDate', 'extraFees', 'extraFeesReason', 'id', 'paidAt', 'paymentMethod', 'paymentStatus', 'photoPath', 'price', 'receiptToken', 'status', 'trackingNumber', 'updatedAt', 'weight'] as const
  $columns = PackageSchema.$columns
  @column()
  declare clientId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare designation: string
  @column.date()
  declare estimatedDeliveryDate: DateTime
  @column()
  declare extraFees: string | null
  @column()
  declare extraFeesReason: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare paymentStatus: string
  @column()
  declare photoPath: string | null
  @column()
  declare price: string
  @column()
  declare receiptToken: string
  @column()
  declare status: string
  @column()
  declare trackingNumber: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weight: string
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'token'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isActive', 'password', 'phone', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
